name: Build Custom Android 12 Go ROM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Set up environment
      run: |
        sudo apt update
        sudo apt install openjdk-11-jdk git curl bc bison build-essential zip unzip -y
        java -version

    - name: Set up repo tool
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo 'export PATH=~/bin:$PATH' >> ~/.bashrc
        source ~/.bashrc

    - name: Initialize AOSP (Go Edition)
      run: |
        mkdir rom && cd rom
        git config --global user.name "Your Name"
        git config --global user.email "you@example.com"
        repo init -u https://android.googlesource.com/platform/manifest -b android-12.0.0_r32 --depth=1
        repo sync -c -j4

    - name: Apply Custom Tweaks
      run: |
        cd rom
        echo "Applying custom features..."
        # أمثلة على التعديلات — يمكن تعديلها أو تطويرها لاحقًا
        # هنا تقدر تضيف ملفات XML لتفعيل AOD و ExtraDim و One-handed mode وغيرها

    - name: Build ROM
      run: |
        cd rom
        source build/envsetup.sh
        lunch aosp_arm-eng
        make -j$(nproc)

    - name: Compress Output
      run: |
        cd rom/out/target/product/generic
        zip -r9 custom_android12go.zip system.img

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: custom-android-rom
        path: rom/out/target/product/generic/custom_android12go.zip
