name: Build Custom ROM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y git curl python3 python-is-python3 zip unzip bc build-essential openjdk-8-jdk

    - name: Install repo tool
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo 'export PATH=$HOME/bin:$PATH' >> $GITHUB_ENV

    - name: Initialize ROM
      run: |
        mkdir rom && cd rom
        ~/bin/repo init -u https://github.com/PixelExperience/manifest -b twelve-go
        ~/bin/repo sync -c --no-tags --no-clone-bundle --optimized-fetch --prune -j4

    - name: Clone device sources
      run: |
        cd rom
        git clone https://github.com/YourUser/device_samsung_a20s.git -b android-12 device/samsung/a20s
        git clone https://github.com/YourUser/vendor_samsung_a20s.git -b android-12 vendor/samsung/a20s
        git clone https://github.com/YourUser/kernel_samsung_a20s.git -b android-12 kernel/samsung/a20s

    - name: Start build
      run: |
        cd rom
        source build/envsetup.sh
        lunch aosp_a20s-userdebug
        make bacon -j$(nproc)

    - name: Upload ROM
      uses: actions/upload-artifact@v3
      with:
        name: Custom-ROM
        path: rom/out/target/product/a20s/*.zip
